[dev]
command = "vite dev"
port = 65510

[build]
publish = "dist/"
command = "yarn build"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/auto-signin.html"
to = "/auto-signin.html"
status = 200

[[redirects]]
from = "/playlist/:id/rss"
to = "/.netlify/functions/get_rss_from_supabase"
status = 200

[[redirects]]
from = "/playlist/:id/thumbnail"
to = "http://localhost:55321/storage/v1/object/public/playlist/thumbnail/:id"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200